Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/xuzhongcong/.virtualenvs/python36/lib/python3.6/site-packages/visdom/server.py", line 1308, in <module>
    download_scripts_and_run()
  File "/home/xuzhongcong/.virtualenvs/python36/lib/python3.6/site-packages/visdom/server.py", line 1304, in download_scripts_and_run
    main()
  File "/home/xuzhongcong/.virtualenvs/python36/lib/python3.6/site-packages/visdom/server.py", line 1299, in main
    print_func=print_func, user_credential=user_credential)
  File "/home/xuzhongcong/.virtualenvs/python36/lib/python3.6/site-packages/visdom/server.py", line 1219, in start_server
    app.listen(port, max_buffer_size=1024 ** 3)
  File "/home/xuzhongcong/.virtualenvs/python36/lib/python3.6/site-packages/tornado/web.py", line 2042, in listen
    server.listen(port, address)
  File "/home/xuzhongcong/.virtualenvs/python36/lib/python3.6/site-packages/tornado/tcpserver.py", line 143, in listen
    sockets = bind_sockets(port, address=address)
  File "/home/xuzhongcong/.virtualenvs/python36/lib/python3.6/site-packages/tornado/netutil.py", line 168, in bind_sockets
    sock.bind(sockaddr)
OSError: [Errno 98] Address already in use
Checking for scripts.
It's Alive!
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/xuzhongcong/.virtualenvs/python36/lib/python3.6/site-packages/visdom/server.py", line 1308, in <module>
    download_scripts_and_run()
  File "/home/xuzhongcong/.virtualenvs/python36/lib/python3.6/site-packages/visdom/server.py", line 1304, in download_scripts_and_run
    main()
  File "/home/xuzhongcong/.virtualenvs/python36/lib/python3.6/site-packages/visdom/server.py", line 1299, in main
    print_func=print_func, user_credential=user_credential)
  File "/home/xuzhongcong/.virtualenvs/python36/lib/python3.6/site-packages/visdom/server.py", line 1219, in start_server
    app.listen(port, max_buffer_size=1024 ** 3)
  File "/home/xuzhongcong/.virtualenvs/python36/lib/python3.6/site-packages/tornado/web.py", line 2042, in listen
    server.listen(port, address)
  File "/home/xuzhongcong/.virtualenvs/python36/lib/python3.6/site-packages/tornado/tcpserver.py", line 143, in listen
    sockets = bind_sockets(port, address=address)
  File "/home/xuzhongcong/.virtualenvs/python36/lib/python3.6/site-packages/tornado/netutil.py", line 168, in bind_sockets
    sock.bind(sockaddr)
OSError: [Errno 98] Address already in use
Checking for scripts.
It's Alive!
/usr/bin/python: No module named visdom
/usr/bin/python: No module named visdom
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/xuzhongcong/.virtualenvs/python36/lib/python3.6/site-packages/visdom/server.py", line 1308, in <module>
    download_scripts_and_run()
  File "/home/xuzhongcong/.virtualenvs/python36/lib/python3.6/site-packages/visdom/server.py", line 1304, in download_scripts_and_run
    main()
  File "/home/xuzhongcong/.virtualenvs/python36/lib/python3.6/site-packages/visdom/server.py", line 1299, in main
    print_func=print_func, user_credential=user_credential)
  File "/home/xuzhongcong/.virtualenvs/python36/lib/python3.6/site-packages/visdom/server.py", line 1219, in start_server
    app.listen(port, max_buffer_size=1024 ** 3)
  File "/home/xuzhongcong/.virtualenvs/python36/lib/python3.6/site-packages/tornado/web.py", line 2042, in listen
    server.listen(port, address)
  File "/home/xuzhongcong/.virtualenvs/python36/lib/python3.6/site-packages/tornado/tcpserver.py", line 143, in listen
    sockets = bind_sockets(port, address=address)
  File "/home/xuzhongcong/.virtualenvs/python36/lib/python3.6/site-packages/tornado/netutil.py", line 168, in bind_sockets
    sock.bind(sockaddr)
OSError: [Errno 98] Address already in use
Checking for scripts.
It's Alive!
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/xuzhongcong/.virtualenvs/python36/lib/python3.6/site-packages/visdom/server.py", line 1308, in <module>
    download_scripts_and_run()
  File "/home/xuzhongcong/.virtualenvs/python36/lib/python3.6/site-packages/visdom/server.py", line 1304, in download_scripts_and_run
    main()
  File "/home/xuzhongcong/.virtualenvs/python36/lib/python3.6/site-packages/visdom/server.py", line 1299, in main
    print_func=print_func, user_credential=user_credential)
  File "/home/xuzhongcong/.virtualenvs/python36/lib/python3.6/site-packages/visdom/server.py", line 1219, in start_server
    app.listen(port, max_buffer_size=1024 ** 3)
  File "/home/xuzhongcong/.virtualenvs/python36/lib/python3.6/site-packages/tornado/web.py", line 2042, in listen
    server.listen(port, address)
  File "/home/xuzhongcong/.virtualenvs/python36/lib/python3.6/site-packages/tornado/tcpserver.py", line 143, in listen
    sockets = bind_sockets(port, address=address)
  File "/home/xuzhongcong/.virtualenvs/python36/lib/python3.6/site-packages/tornado/netutil.py", line 168, in bind_sockets
    sock.bind(sockaddr)
OSError: [Errno 98] Address already in use
Checking for scripts.
It's Alive!
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/xuzhongcong/.virtualenvs/python36/lib/python3.6/site-packages/visdom/server.py", line 1308, in <module>
    download_scripts_and_run()
  File "/home/xuzhongcong/.virtualenvs/python36/lib/python3.6/site-packages/visdom/server.py", line 1304, in download_scripts_and_run
    main()
  File "/home/xuzhongcong/.virtualenvs/python36/lib/python3.6/site-packages/visdom/server.py", line 1299, in main
    print_func=print_func, user_credential=user_credential)
  File "/home/xuzhongcong/.virtualenvs/python36/lib/python3.6/site-packages/visdom/server.py", line 1219, in start_server
    app.listen(port, max_buffer_size=1024 ** 3)
  File "/home/xuzhongcong/.virtualenvs/python36/lib/python3.6/site-packages/tornado/web.py", line 2042, in listen
    server.listen(port, address)
  File "/home/xuzhongcong/.virtualenvs/python36/lib/python3.6/site-packages/tornado/tcpserver.py", line 143, in listen
    sockets = bind_sockets(port, address=address)
  File "/home/xuzhongcong/.virtualenvs/python36/lib/python3.6/site-packages/tornado/netutil.py", line 168, in bind_sockets
    sock.bind(sockaddr)
OSError: [Errno 98] Address already in use
Checking for scripts.
It's Alive!
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/xuzhongcong/.virtualenvs/python36/lib/python3.6/site-packages/visdom/server.py", line 1308, in <module>
    download_scripts_and_run()
  File "/home/xuzhongcong/.virtualenvs/python36/lib/python3.6/site-packages/visdom/server.py", line 1304, in download_scripts_and_run
    main()
  File "/home/xuzhongcong/.virtualenvs/python36/lib/python3.6/site-packages/visdom/server.py", line 1299, in main
    print_func=print_func, user_credential=user_credential)
  File "/home/xuzhongcong/.virtualenvs/python36/lib/python3.6/site-packages/visdom/server.py", line 1219, in start_server
    app.listen(port, max_buffer_size=1024 ** 3)
  File "/home/xuzhongcong/.virtualenvs/python36/lib/python3.6/site-packages/tornado/web.py", line 2042, in listen
    server.listen(port, address)
  File "/home/xuzhongcong/.virtualenvs/python36/lib/python3.6/site-packages/tornado/tcpserver.py", line 143, in listen
    sockets = bind_sockets(port, address=address)
  File "/home/xuzhongcong/.virtualenvs/python36/lib/python3.6/site-packages/tornado/netutil.py", line 168, in bind_sockets
    sock.bind(sockaddr)
OSError: [Errno 98] Address already in use
Checking for scripts.
It's Alive!
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/xuzhongcong/.virtualenvs/python36/lib/python3.6/site-packages/visdom/server.py", line 1308, in <module>
    download_scripts_and_run()
  File "/home/xuzhongcong/.virtualenvs/python36/lib/python3.6/site-packages/visdom/server.py", line 1304, in download_scripts_and_run
    main()
  File "/home/xuzhongcong/.virtualenvs/python36/lib/python3.6/site-packages/visdom/server.py", line 1299, in main
    print_func=print_func, user_credential=user_credential)
  File "/home/xuzhongcong/.virtualenvs/python36/lib/python3.6/site-packages/visdom/server.py", line 1219, in start_server
    app.listen(port, max_buffer_size=1024 ** 3)
  File "/home/xuzhongcong/.virtualenvs/python36/lib/python3.6/site-packages/tornado/web.py", line 2042, in listen
    server.listen(port, address)
  File "/home/xuzhongcong/.virtualenvs/python36/lib/python3.6/site-packages/tornado/tcpserver.py", line 143, in listen
    sockets = bind_sockets(port, address=address)
  File "/home/xuzhongcong/.virtualenvs/python36/lib/python3.6/site-packages/tornado/netutil.py", line 168, in bind_sockets
    sock.bind(sockaddr)
OSError: [Errno 98] Address already in use
Checking for scripts.
It's Alive!
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/xuzhongcong/.virtualenvs/python36/lib/python3.6/site-packages/visdom/server.py", line 1308, in <module>
    download_scripts_and_run()
  File "/home/xuzhongcong/.virtualenvs/python36/lib/python3.6/site-packages/visdom/server.py", line 1304, in download_scripts_and_run
    main()
  File "/home/xuzhongcong/.virtualenvs/python36/lib/python3.6/site-packages/visdom/server.py", line 1299, in main
    print_func=print_func, user_credential=user_credential)
  File "/home/xuzhongcong/.virtualenvs/python36/lib/python3.6/site-packages/visdom/server.py", line 1219, in start_server
    app.listen(port, max_buffer_size=1024 ** 3)
  File "/home/xuzhongcong/.virtualenvs/python36/lib/python3.6/site-packages/tornado/web.py", line 2042, in listen
    server.listen(port, address)
  File "/home/xuzhongcong/.virtualenvs/python36/lib/python3.6/site-packages/tornado/tcpserver.py", line 143, in listen
    sockets = bind_sockets(port, address=address)
  File "/home/xuzhongcong/.virtualenvs/python36/lib/python3.6/site-packages/tornado/netutil.py", line 168, in bind_sockets
    sock.bind(sockaddr)
OSError: [Errno 98] Address already in use
Checking for scripts.
It's Alive!
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/xuzhongcong/.virtualenvs/python36/lib/python3.6/site-packages/visdom/server.py", line 1308, in <module>
    download_scripts_and_run()
  File "/home/xuzhongcong/.virtualenvs/python36/lib/python3.6/site-packages/visdom/server.py", line 1304, in download_scripts_and_run
    main()
  File "/home/xuzhongcong/.virtualenvs/python36/lib/python3.6/site-packages/visdom/server.py", line 1299, in main
    print_func=print_func, user_credential=user_credential)
  File "/home/xuzhongcong/.virtualenvs/python36/lib/python3.6/site-packages/visdom/server.py", line 1219, in start_server
    app.listen(port, max_buffer_size=1024 ** 3)
  File "/home/xuzhongcong/.virtualenvs/python36/lib/python3.6/site-packages/tornado/web.py", line 2042, in listen
    server.listen(port, address)
  File "/home/xuzhongcong/.virtualenvs/python36/lib/python3.6/site-packages/tornado/tcpserver.py", line 143, in listen
    sockets = bind_sockets(port, address=address)
  File "/home/xuzhongcong/.virtualenvs/python36/lib/python3.6/site-packages/tornado/netutil.py", line 168, in bind_sockets
    sock.bind(sockaddr)
OSError: [Errno 98] Address already in use
Checking for scripts.
It's Alive!
/home/xuzhongcong/.virtualenvs/python36/bin/python: Error while finding module specification for 'svisdom.server' (ModuleNotFoundError: No module named 'svisdom')
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/xuzhongcong/.virtualenvs/python36/lib/python3.6/site-packages/visdom/server.py", line 1308, in <module>
    download_scripts_and_run()
  File "/home/xuzhongcong/.virtualenvs/python36/lib/python3.6/site-packages/visdom/server.py", line 1304, in download_scripts_and_run
    main()
  File "/home/xuzhongcong/.virtualenvs/python36/lib/python3.6/site-packages/visdom/server.py", line 1299, in main
    print_func=print_func, user_credential=user_credential)
  File "/home/xuzhongcong/.virtualenvs/python36/lib/python3.6/site-packages/visdom/server.py", line 1219, in start_server
    app.listen(port, max_buffer_size=1024 ** 3)
  File "/home/xuzhongcong/.virtualenvs/python36/lib/python3.6/site-packages/tornado/web.py", line 2042, in listen
    server.listen(port, address)
  File "/home/xuzhongcong/.virtualenvs/python36/lib/python3.6/site-packages/tornado/tcpserver.py", line 143, in listen
    sockets = bind_sockets(port, address=address)
  File "/home/xuzhongcong/.virtualenvs/python36/lib/python3.6/site-packages/tornado/netutil.py", line 168, in bind_sockets
    sock.bind(sockaddr)
OSError: [Errno 98] Address already in use
Checking for scripts.
It's Alive!
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/xuzhongcong/.virtualenvs/python36/lib/python3.6/site-packages/visdom/server.py", line 1308, in <module>
    download_scripts_and_run()
  File "/home/xuzhongcong/.virtualenvs/python36/lib/python3.6/site-packages/visdom/server.py", line 1304, in download_scripts_and_run
    main()
  File "/home/xuzhongcong/.virtualenvs/python36/lib/python3.6/site-packages/visdom/server.py", line 1299, in main
    print_func=print_func, user_credential=user_credential)
  File "/home/xuzhongcong/.virtualenvs/python36/lib/python3.6/site-packages/visdom/server.py", line 1219, in start_server
    app.listen(port, max_buffer_size=1024 ** 3)
  File "/home/xuzhongcong/.virtualenvs/python36/lib/python3.6/site-packages/tornado/web.py", line 2042, in listen
    server.listen(port, address)
  File "/home/xuzhongcong/.virtualenvs/python36/lib/python3.6/site-packages/tornado/tcpserver.py", line 143, in listen
    sockets = bind_sockets(port, address=address)
  File "/home/xuzhongcong/.virtualenvs/python36/lib/python3.6/site-packages/tornado/netutil.py", line 168, in bind_sockets
    sock.bind(sockaddr)
OSError: [Errno 98] Address already in use
Checking for scripts.
It's Alive!
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/xuzhongcong/.virtualenvs/python36/lib/python3.6/site-packages/visdom/server.py", line 1308, in <module>
    download_scripts_and_run()
  File "/home/xuzhongcong/.virtualenvs/python36/lib/python3.6/site-packages/visdom/server.py", line 1304, in download_scripts_and_run
    main()
  File "/home/xuzhongcong/.virtualenvs/python36/lib/python3.6/site-packages/visdom/server.py", line 1299, in main
    print_func=print_func, user_credential=user_credential)
  File "/home/xuzhongcong/.virtualenvs/python36/lib/python3.6/site-packages/visdom/server.py", line 1219, in start_server
    app.listen(port, max_buffer_size=1024 ** 3)
  File "/home/xuzhongcong/.virtualenvs/python36/lib/python3.6/site-packages/tornado/web.py", line 2042, in listen
    server.listen(port, address)
  File "/home/xuzhongcong/.virtualenvs/python36/lib/python3.6/site-packages/tornado/tcpserver.py", line 143, in listen
    sockets = bind_sockets(port, address=address)
  File "/home/xuzhongcong/.virtualenvs/python36/lib/python3.6/site-packages/tornado/netutil.py", line 168, in bind_sockets
    sock.bind(sockaddr)
OSError: [Errno 98] Address already in use
Checking for scripts.
It's Alive!
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/xuzhongcong/.virtualenvs/python36/lib/python3.6/site-packages/visdom/server.py", line 1308, in <module>
    download_scripts_and_run()
  File "/home/xuzhongcong/.virtualenvs/python36/lib/python3.6/site-packages/visdom/server.py", line 1304, in download_scripts_and_run
    main()
  File "/home/xuzhongcong/.virtualenvs/python36/lib/python3.6/site-packages/visdom/server.py", line 1299, in main
    print_func=print_func, user_credential=user_credential)
  File "/home/xuzhongcong/.virtualenvs/python36/lib/python3.6/site-packages/visdom/server.py", line 1219, in start_server
    app.listen(port, max_buffer_size=1024 ** 3)
  File "/home/xuzhongcong/.virtualenvs/python36/lib/python3.6/site-packages/tornado/web.py", line 2042, in listen
    server.listen(port, address)
  File "/home/xuzhongcong/.virtualenvs/python36/lib/python3.6/site-packages/tornado/tcpserver.py", line 143, in listen
    sockets = bind_sockets(port, address=address)
  File "/home/xuzhongcong/.virtualenvs/python36/lib/python3.6/site-packages/tornado/netutil.py", line 168, in bind_sockets
    sock.bind(sockaddr)
OSError: [Errno 98] Address already in use
Checking for scripts.
It's Alive!
